import { getFounderReports } from "@/app/actions/founder";
import SectionHeader from "@/components/ui/SectionHeader";
import { FileText, Download, Calendar, ArrowRight } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";

export default async function ReportsPage() {
  const reports = await getFounderReports();

  if (reports === null) {
    redirect("/logout");
  }

  return (
    <div className="p-8 space-y-8">
      <SectionHeader 
        title="Business Reports"
        description="Comprehensive analysis reports generated by our AI and your consultants."
      />

      {reports.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {reports.map((report) => (
            <div key={report.id} className="group bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-[32px] p-8 hover:shadow-2xl hover:shadow-blue-500/10 transition-all duration-500 relative overflow-hidden">
              <div className="w-14 h-14 bg-slate-50 dark:bg-slate-800 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-500">
                <FileText className="w-7 h-7 text-blue-500" />
              </div>
              
              <p className="text-[10px] uppercase font-black tracking-widest text-slate-400 mb-2">{report.reportType.replace('_', ' ')}</p>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-6 group-hover:text-blue-500 transition-colors">{report.title}</h3>
              
              <div className="flex items-center gap-3 text-sm text-slate-500 dark:text-slate-400 mb-8">
                <Calendar className="w-4 h-4" />
                <span className="font-medium">Generated on {new Date(report.createdAt).toLocaleDateString()}</span>
              </div>

              <div className="flex gap-3">
                <button className="flex-1 py-4 bg-slate-50 dark:bg-slate-800 hover:bg-slate-900 dark:hover:bg-white text-slate-900 dark:text-white dark:hover:text-slate-900 hover:text-white rounded-2xl transition-all duration-300 font-bold text-sm flex items-center justify-center gap-2">
                  <Download className="w-4 h-4" />
                  Download
                </button>
                <Link 
                  href={`/founder/reports/${report.id}`} 
                  className="p-4 bg-blue-500 text-white rounded-2xl hover:bg-blue-600 transition-all shadow-lg shadow-blue-500/20 group/btn"
                >
                  <ArrowRight className="w-5 h-5 group-hover/btn:translate-x-1 transition-transform" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="bg-white dark:bg-slate-900 border border-dashed border-slate-200 dark:border-slate-800 rounded-[40px] p-20 text-center">
          <FileText className="w-16 h-16 text-slate-200 dark:text-slate-700 mx-auto mb-6" strokeWidth={1} />
          <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-2">No Reports Available</h3>
          <p className="text-slate-400 max-w-sm mx-auto">
            Once analysis reports are generated for your business, they will appear here for download and review.
          </p>
        </div>
      )}
    </div>
  );
}
